[build]
  # The command Netlify should run to build your project
  command = "npm run build"
  
  # The directory to publish (where your build output goes)
  publish = "dist"

  # Use Node.js version if necessary (optional)
  # environment = { NODE_VERSION = "16.x" } # uncomment if you need a specific Node version

[dev]
  # Set your development server port and command for Netlify Dev
  framework = "vite"

[[headers]]
  # Set proper MIME types and cache control
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  # Redirect all requests to the index.html (for single-page applications)
  from = "/*"
  to = "/index.html"
  status = 200
